In [1]:
from games.SIR import SIR_Game
from games.ring import ring_Game
import numpy as np 
import torch 
W = np.array([
    [0.8,0.4],
    [0.4, 0.8]
])
K = len(W)
game = SIR_Game(W,K=2)
game1 = ring_Game(W,K=2)

In [3]:
game1.bar 

5.0

In [4]:
game1.pop_inf()
q = game1.Gamma_q_func(0)
q.shape 

(11, 3)

In [8]:
s = 10
game1.mirror(0,s,q[s],eta=4)

array([0.45047254, 0.29808367, 0.25144379])

In [5]:
game.get_transition(0)
game.pop_inf(iter=1000)
game.mean_field

array([[0.22222222, 0.38888889, 0.38888889],
       [0.22222222, 0.38888889, 0.38888889]])

In [2]:
mu = game.mean_field
print(mu.shape)
pi = game.pi 
print(pi.shape)


(2, 3)
(2, 3, 3)


In [9]:
from scipy.stats import entropy
from scipy.optimize import minimize
import numpy as np 


array([-2., 10.])

In [6]:
game.z
game1.pop_inf()
game1.mean_field

array([[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]])

In [7]:
game1.Vh_func(0)

AttributeError: 'ring_Game' object has no attribute 'controller'

array([[0.33333333, 0.06666667, 0.        ],
       [0.        , 0.2       , 0.13333333],
       [0.13333333, 0.        , 0.2       ]])

In [22]:
pi.shape 
transition = np.zeros((game1.nstate,game1.nstate))
k = 0 
for s in range(game1.nstate):
    for s1 in range(game1.nstate):
        for a in range(game1.naction):
            transition[s,s1] = game1.transition_probs(k,s,a)[s1]*game1.pi[k,s,a]

)
print(np.sum(transition,axis=1))


[0.         0.08333333 0.16666667 0.08333333 0.         0.
 0.         0.         0.         0.        ]
[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333 0.33333333
 0.33333333 0.33333333 0.33333333 0.33333333]
